#spring:
#  application:
#    name: eureka
#server:
#  port: 8761
#eureka:
#  client:
#    service-url:
#      defaultZone:  http://localhost:8762/eureka/,http://localhost:8763/eureka/
#    register-with-eureka: false


spring:
  application:
    name: eureka
  profiles: server1
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8762/eureka/,http://localhost:8763/eureka/
    register-with-eureka: false
---

spring:
  application:
    name: eureka2
  profiles: server2
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/,http://localhost:8763/eureka/
    register-with-eureka: false
---

spring:
  application:
    name: eureka3
  profiles: server3
server:
  port: 8763
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8762/eureka/,http://localhost:8763/eureka/
    register-with-eureka: false

---

